name: OpenSSF Scorecard

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 2 * * 0'  # Runs every Sunday at 2 AM UTC

jobs:
  scorecard:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Scorecard
        id: scorecard
        uses: ossf/scorecard-action@v2
        with:
          results_file: results.json

      - name: Upload Scorecard results
        uses: actions/upload-artifact@v3
        with:
          name: scorecard-results
          path: results.json
